### ISSUE TITLE
flights_sort = flights[['ORG_AIR', 'DEST_AIR']].apply(sorted, axis=1)

### ISSUE THREAD

**Issue by TheBubblePopped** [PacktPublishing/Pandas-Cookbook#1]
pycharm produces a different series than the one in the example. The column keys are lost this way

**Comment by rwkopcke** [comment]
ipython (in juypter notebook) for this line of code (cell 95) produces a pandas.core.series.Series, which has no column label(s). Each item in the series is a list with two airport codes. Also the DF puportedly produced by cell 95 as shown in the post does not seem to be sorted in any way.

flights_sort = flights[['ORG_AIR', 'DEST_AIR']].apply(sorted, axis=1)
flights_sort.head()
0    [LAX, SLC]
1    [DEN, IAD]
2    [DFW, VPS]
3    [DCA, DFW]
4    [LAX, MCI]
dtype: object

type(flights_sort)
pandas.core.series.Series

if I set axis=0 (or 'index'):
flights_sort = flights[['ORG_AIR', 'DEST_AIR']].apply(sorted, axis=0)
flights_sort.head()
	ORG_AIR	DEST_AIR
0	ATL	ABE
1	ATL	ABE
2	ATL	ABE
3	ATL	ABE
4	ATL	ABE

type(flights_sort)
pandas.core.frame.DataFrame

**Comment by lindangulopez** [comment]
tnx!
