### ISSUE TITLE
ValueError: Table tracks not found

### ISSUE THREAD

**Issue by rwkopcke** [PacktPublishing/Pandas-Cookbook#2]
I solved this problem by trying different expressions for paths to the chinook.db file for the create_engine(), which eventually produced a useful error message. The following line works if you provide an absolute address for the dir that holds the chinook.db file in the string that I called "path_to_file":
# engine = create_engine('sqlite:////' + path_to_file + 'chinook.db')
For absolute addresses, create_engine expects //// not ///.

# this was my original statement of the problem

from sqlalchemy import create_engine
engine = create_engine('sqlite:///chinook.db')
tracks = pd.read_sql_table('tracks', engine)
tracks.head()

InvalidRequestError                       Traceback (most recent call last)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/io/sql.py in read_sql_table(table_name, con, schema, index_col, coerce_float, parse_dates, columns, chunksize)
    239     try:
--> 240         meta.reflect(only=[table_name], views=True)
    241     except sqlalchemy.exc.InvalidRequestError:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/sql/schema.py in reflect(self, bind, schema, views, only, extend_existing, autoload_replace, **dialect_kwargs)
   4148                         "Could not reflect: requested table(s) not available "
-> 4149                         "in %r%s: (%s)" % (bind.engine, s, ", ".join(missing))
   4150                     )

InvalidRequestError: Could not reflect: requested table(s) not available in Engine(sqlite:///chinook.db): (tracks)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-117-63a1788c80a2> in <module>()
----> 1 tracks = pd.read_sql_table('tracks', engine)
      2 tracks.head()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/io/sql.py in read_sql_table(table_name, con, schema, index_col, coerce_float, parse_dates, columns, chunksize)
    240         meta.reflect(only=[table_name], views=True)
    241     except sqlalchemy.exc.InvalidRequestError:
--> 242         raise ValueError("Table %s not found" % table_name)
    243 
    244     pandas_sql = SQLDatabase(con, meta=meta)

ValueError: Table tracks not found

**Comment by tdpetrou** [comment]
Yes, this is correct. You need 4 forward slashes for an absolute path. Heres more in the pandas documentation - https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#engine-connection-examples
