### ISSUE TITLE
Chapter 11, In [49]

### ISSUE THREAD

**Issue by rwkopcke** [PacktPublishing/Pandas-Cookbook#3]
The code, as written, does not produce the output shown in Out [49] in ipython in a jupyter notebook.

In the scatter plot, color=  expects one input, not a list of two inputs.
In the line plot, the x axis has no labels.

**Comment by tdpetrou** [comment]
Hey @rwkopcke thanks for reporting this. Looks like this accidentally worked when the book was written when pandas was on version 20. It now (correctly) does not work. That middle scatterplot should not have any color applied to it and it doesn't make sense to even color the points. So just remove `color=color` from the plotting command.
